import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <header className="p-5 h-50 flex bg-gray-50">
            <div className="card card-side">
              <figure>
                <Image
                  width={20}
                  height={20}
                  src="/public/spotify.png" 
                  alt=""/>
              </figure>
            </div>
            <a
              className="my-auto ml-6 text-6xl text-green-500" 
              href="/">
                Spotify Overlay
            </a>
          </header>
          <div className="flex h-200">
            {children}
          </div>
          <footer>
            fafs
          </footer>
      </body>
    </html>
  );
}
